### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by gesoges0** [gesoges0/nba-db#3]
# database
- [x] parser 化
- [x] initialize (時間をかけてapiから)
- - [x] player season
- - [x] team season
- - [x] player all time 
- - [ ] team all time  
- [ ] dump batch 
- - python からのmysqldumpに該当する機能を叩けるようにする？
- [ ] initialize batch(mountしたvolumeのdumpした.sqlファイルから)
- [ ] update batch
- [ ] class 設計の自動化
- [x] test (black, flake8, isort)
- [x] test (mypy)
- [x] test (xenon, radon)
- [ ] test coverage
- [ ] test (db-fixture)
- [ ] test (pytest基盤)
- [x] docker-compose でdbを先に書き, pysqlclientでDockerfileで実行せずにdocker-compose で実行
- [x] srcをマウント
- [x] test yaml
- [x] test (docker linter) 
- [ ] initialize batch など docker compose exec 系をShell Scriptから叩けるようにする
- [ ] document 生成自動化
